/**
 * Export Utilities — Text, PDF & Excel export for reports.
 *
 * Text:  Available to all plans (plain text)
 * PDF:   Available to all plans (uses jspdf + jspdf-autotable)
 * Excel: Available to all plans (uses SheetJS/xlsx)
 *
 * Features:
 *  - School badge/logo on PDF header
 *  - Plan-based branding:
 *      Free/Starter  → "Generated by School Manager © YYYY"
 *      Premium       → "Generated by [School Name] digital system on [date]"
 *  - Single-report export & share (Text, PDF, Excel)
 *  - Comprehensive all-in-one report export & share
 */
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

/* ═══════════════════════════════════════════
 *  Helpers
 * ═══════════════════════════════════════════ */

/** Build a descriptive, filesystem-safe file name. */
export const buildFileName = (schoolName, title, subtitle = '') => {
  const safe = (str) => str.replace(/[^a-zA-Z0-9 ]/g, '').trim().replace(/\s+/g, '_');
  const parts = [safe(schoolName), safe(title)];
  if (subtitle) parts.push(safe(subtitle));
  parts.push(new Date().toISOString().slice(0, 10));
  return parts.join('_');
};

/**
 * Get branding footer text based on plan.
 *  - Free/Starter: "Generated by School Manager © YYYY"
 *  - Premium:      "Generated by [School Name] digital system on [full date]"
 */
const getBrandingText = (schoolName, isPremium) => {
  const now = new Date();
  if (isPremium) {
    const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    return `Generated by ${schoolName} digital system on ${dateStr}`;
  }
  return `Generated by School Manager \u00A9 ${now.getFullYear()}`;
};

/** Load an image URL and return { dataUrl, width, height } or null. */
const loadLogo = async (url) => {
  if (!url) return null;
  try {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    await new Promise((resolve, reject) => { img.onload = resolve; img.onerror = reject; img.src = url; });
    const canvas = document.createElement('canvas');
    canvas.width = img.naturalWidth;
    canvas.height = img.naturalHeight;
    canvas.getContext('2d').drawImage(img, 0, 0);
    return { dataUrl: canvas.toDataURL('image/png'), width: img.naturalWidth, height: img.naturalHeight };
  } catch { return null; }
};

/** Draw branded footer on every page of a jsPDF document. */
const addBrandedFooters = (doc, brandingText) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150);
    doc.text(brandingText, pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 6, { align: 'center' });
  }
};

/** Draw PDF header (logo + school name + title + subtitle + divider). Returns Y. */
const drawPDFHeader = (doc, { schoolName, title, subtitle, logo }) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 14;
  if (logo) {
    const maxH = 14, ratio = logo.width / logo.height;
    const w = Math.min(maxH * ratio, 22);
    doc.addImage(logo.dataUrl, 'PNG', (pageWidth - w) / 2, y, w, maxH);
    y += maxH + 3;
  }
  doc.setFontSize(16); doc.setFont('helvetica', 'bold'); doc.setTextColor(30, 58, 95);
  doc.text(schoolName, pageWidth / 2, y + 4, { align: 'center' }); y += 10;
  doc.setFontSize(12); doc.setFont('helvetica', 'normal'); doc.setTextColor(60);
  doc.text(title, pageWidth / 2, y, { align: 'center' }); y += 6;
  if (subtitle) {
    doc.setFontSize(9); doc.setTextColor(120);
    doc.text(subtitle, pageWidth / 2, y, { align: 'center' }); y += 5;
  }
  doc.setDrawColor(200); doc.line(14, y, pageWidth - 14, y); y += 4;
  doc.setTextColor(0);
  return y;
};

/* ═══════════════════════════════════════════
 *  TEXT Builders
 * ═══════════════════════════════════════════ */

/**
 * Build a plain-text table from columns + rows.
 */
const buildTextTable = (columns, rows) => {
  // Calculate column widths
  const widths = columns.map((col, i) => {
    let max = String(col).length;
    rows.forEach((row) => {
      const val = row[i] != null ? String(row[i]) : '';
      if (val.length > max) max = val.length;
    });
    return Math.min(max + 2, 35);
  });

  const pad = (str, w) => {
    const s = String(str ?? '');
    return s.length >= w ? s.slice(0, w) : s + ' '.repeat(w - s.length);
  };

  const divider = widths.map((w) => '-'.repeat(w)).join(' | ');
  const headerLine = columns.map((c, i) => pad(c, widths[i])).join(' | ');
  const dataLines = rows.map((row) =>
    row.map((cell, i) => pad(cell, widths[i])).join(' | ')
  );

  return [headerLine, divider, ...dataLines].join('\n');
};

/** Build single-report text content. */
const buildTextContent = ({ title, schoolName, columns, rows, subtitle = '', isPremium = false }) => {
  const branding = getBrandingText(schoolName, isPremium);
  const lines = [];
  lines.push('='.repeat(60));
  lines.push(schoolName);
  lines.push(title);
  if (subtitle) lines.push(subtitle);
  lines.push('='.repeat(60));
  lines.push('');
  lines.push(buildTextTable(columns, rows));
  lines.push('');
  lines.push('-'.repeat(60));
  lines.push(branding);
  return lines.join('\n');
};

/** Build comprehensive multi-section text content. */
const buildComprehensiveTextContent = ({ schoolName, isPremium = false, sections = [] }) => {
  const branding = getBrandingText(schoolName, isPremium);
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const lines = [];

  lines.push('='.repeat(60));
  lines.push(schoolName);
  lines.push('Comprehensive School Report');
  lines.push(dateStr);
  lines.push('='.repeat(60));

  const filtered = sections.filter((s) => s.rows && s.rows.length > 0);
  if (filtered.length === 0) {
    lines.push('');
    lines.push('No report data available.');
  } else {
    filtered.forEach((section) => {
      lines.push('');
      lines.push('─'.repeat(60));
      lines.push(`  ${section.title}`);
      if (section.subtitle) lines.push(`  ${section.subtitle}`);
      lines.push('─'.repeat(60));
      lines.push('');
      lines.push(buildTextTable(section.columns, section.rows));
    });
  }

  lines.push('');
  lines.push('='.repeat(60));
  lines.push(branding);
  return lines.join('\n');
};

/* ═══════════════════════════════════════════
 *  PDF Builders
 * ═══════════════════════════════════════════ */

const buildPDFDoc = async ({ title, schoolName, columns, rows, subtitle = '', orientation = 'portrait', logoUrl, isPremium = false }) => {
  const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });
  const logo = await loadLogo(logoUrl);
  const startY = drawPDFHeader(doc, { schoolName, title, subtitle, logo });
  autoTable(doc, {
    startY, head: [columns], body: rows,
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [30, 58, 95], textColor: 255, fontStyle: 'bold', fontSize: 9 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    margin: { left: 14, right: 14, bottom: 22 },
  });
  addBrandedFooters(doc, getBrandingText(schoolName, isPremium));
  return doc;
};

const buildComprehensivePDF = async ({ schoolName, logoUrl, isPremium = false, sections = [] }) => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const logo = await loadLogo(logoUrl);

  let y = 20;
  if (logo) {
    const maxH = 20, ratio = logo.width / logo.height, w = Math.min(maxH * ratio, 30);
    doc.addImage(logo.dataUrl, 'PNG', (pageWidth - w) / 2, y, w, maxH);
    y += maxH + 6;
  }
  doc.setFontSize(20); doc.setFont('helvetica', 'bold'); doc.setTextColor(30, 58, 95);
  doc.text(schoolName, pageWidth / 2, y + 4, { align: 'center' }); y += 14;
  doc.setFontSize(14); doc.setFont('helvetica', 'normal'); doc.setTextColor(80);
  doc.text('Comprehensive School Report', pageWidth / 2, y, { align: 'center' }); y += 8;
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.setFontSize(10); doc.setTextColor(130);
  doc.text(dateStr, pageWidth / 2, y, { align: 'center' }); y += 8;
  doc.setDrawColor(200); doc.line(14, y, pageWidth - 14, y); doc.setTextColor(0);

  const filtered = sections.filter((s) => s.rows && s.rows.length > 0);
  filtered.forEach((section, idx) => {
    if (idx === 0) { y += 6; } else { doc.addPage(); y = 18; }
    doc.setFontSize(14); doc.setFont('helvetica', 'bold'); doc.setTextColor(30, 58, 95);
    doc.text(section.title, 14, y); y += 2;
    if (section.subtitle) {
      doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(120);
      doc.text(section.subtitle, 14, y + 4); y += 8;
    }
    doc.setDrawColor(220); doc.line(14, y + 1, pageWidth - 14, y + 1); y += 4; doc.setTextColor(0);
    autoTable(doc, {
      startY: y, head: [section.columns], body: section.rows,
      styles: { fontSize: 8.5, cellPadding: 2.5 },
      headStyles: { fillColor: [30, 58, 95], textColor: 255, fontStyle: 'bold', fontSize: 8.5 },
      alternateRowStyles: { fillColor: [245, 247, 250] },
      margin: { left: 14, right: 14, bottom: 22 },
    });
  });
  if (filtered.length === 0) {
    doc.setFontSize(12); doc.setTextColor(150);
    doc.text('No report data available.', pageWidth / 2, y + 20, { align: 'center' });
  }
  addBrandedFooters(doc, getBrandingText(schoolName, isPremium));
  return doc;
};

/* ═══════════════════════════════════════════
 *  Excel Builders
 * ═══════════════════════════════════════════ */

const buildExcelWB = ({ title, schoolName, columns, rows, subtitle = '', isPremium = false }) => {
  const branding = getBrandingText(schoolName, isPremium);
  const wsData = [[schoolName], [title]];
  if (subtitle) wsData.push([subtitle]);
  wsData.push([], columns);
  rows.forEach((row) => wsData.push(row));
  wsData.push([], [branding]);
  const ws = XLSX.utils.aoa_to_sheet(wsData);
  ws['!cols'] = columns.map((col, i) => {
    let max = col.length;
    rows.forEach((row) => { const v = row[i] != null ? String(row[i]) : ''; if (v.length > max) max = v.length; });
    return { wch: Math.min(max + 4, 40) };
  });
  const lastCol = columns.length - 1;
  ws['!merges'] = [
    { s: { r: 0, c: 0 }, e: { r: 0, c: lastCol } },
    { s: { r: 1, c: 0 }, e: { r: 1, c: lastCol } },
  ];
  if (subtitle) ws['!merges'].push({ s: { r: 2, c: 0 }, e: { r: 2, c: lastCol } });
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, title.slice(0, 31));
  return wb;
};

const buildComprehensiveExcelWB = ({ schoolName, isPremium = false, sections = [] }) => {
  const branding = getBrandingText(schoolName, isPremium);
  const wb = XLSX.utils.book_new();
  const filtered = sections.filter((s) => s.rows && s.rows.length > 0);
  filtered.forEach((section) => {
    const wsData = [[schoolName], [section.title]];
    if (section.subtitle) wsData.push([section.subtitle]);
    wsData.push([], section.columns);
    section.rows.forEach((row) => wsData.push(row));
    wsData.push([], [branding]);
    const ws = XLSX.utils.aoa_to_sheet(wsData);
    ws['!cols'] = section.columns.map((col, i) => {
      let max = col.length;
      section.rows.forEach((row) => { const v = row[i] != null ? String(row[i]) : ''; if (v.length > max) max = v.length; });
      return { wch: Math.min(max + 4, 40) };
    });
    const lastCol = section.columns.length - 1;
    ws['!merges'] = [
      { s: { r: 0, c: 0 }, e: { r: 0, c: lastCol } },
      { s: { r: 1, c: 0 }, e: { r: 1, c: lastCol } },
    ];
    if (section.subtitle) ws['!merges'].push({ s: { r: 2, c: 0 }, e: { r: 2, c: lastCol } });
    XLSX.utils.book_append_sheet(wb, ws, section.title.slice(0, 31));
  });
  if (filtered.length === 0) {
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([[schoolName], ['No data available']]), 'Report');
  }
  return wb;
};

/* ═══════════════════════════════════════════
 *  Public API — Single Report
 * ═══════════════════════════════════════════ */

// ── Text ──
export const exportToText = (opts) => {
  const text = buildTextContent(opts);
  const fileName = buildFileName(opts.schoolName, opts.title, opts.subtitle);
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `${fileName}.txt`;
  a.click();
  URL.revokeObjectURL(a.href);
};

export const generateTextFile = (opts) => {
  const text = buildTextContent(opts);
  const fileName = buildFileName(opts.schoolName, opts.title, opts.subtitle);
  return new File([text], `${fileName}.txt`, { type: 'text/plain' });
};

// ── PDF ──
export const exportToPDF = async (opts) => {
  const doc = await buildPDFDoc(opts);
  doc.save(`${buildFileName(opts.schoolName, opts.title, opts.subtitle)}.pdf`);
};

export const generatePDFFile = async (opts) => {
  const doc = await buildPDFDoc(opts);
  const fn = buildFileName(opts.schoolName, opts.title, opts.subtitle);
  return new File([doc.output('blob')], `${fn}.pdf`, { type: 'application/pdf' });
};

// ── Excel ──
export const exportToExcel = (opts) => {
  const wb = buildExcelWB(opts);
  XLSX.writeFile(wb, `${buildFileName(opts.schoolName, opts.title, opts.subtitle)}.xlsx`);
};

export const generateExcelFile = (opts) => {
  const wb = buildExcelWB(opts);
  const fn = buildFileName(opts.schoolName, opts.title, opts.subtitle);
  const buf = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new File([buf], `${fn}.xlsx`, { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
};

/* ═══════════════════════════════════════════
 *  Public API — Comprehensive (All-in-One)
 * ═══════════════════════════════════════════ */

// ── Text ──
export const exportAllToText = (opts) => {
  const text = buildComprehensiveTextContent(opts);
  const fileName = buildFileName(opts.schoolName, 'Comprehensive Report');
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `${fileName}.txt`;
  a.click();
  URL.revokeObjectURL(a.href);
};

export const generateAllTextFile = (opts) => {
  const text = buildComprehensiveTextContent(opts);
  const fn = buildFileName(opts.schoolName, 'Comprehensive Report');
  return new File([text], `${fn}.txt`, { type: 'text/plain' });
};

// ── PDF ──
export const exportAllToPDF = async (opts) => {
  const doc = await buildComprehensivePDF(opts);
  doc.save(`${buildFileName(opts.schoolName, 'Comprehensive Report')}.pdf`);
};

export const generateAllPDFFile = async (opts) => {
  const doc = await buildComprehensivePDF(opts);
  const fn = buildFileName(opts.schoolName, 'Comprehensive Report');
  return new File([doc.output('blob')], `${fn}.pdf`, { type: 'application/pdf' });
};

// ── Excel ──
export const exportAllToExcel = (opts) => {
  const wb = buildComprehensiveExcelWB(opts);
  XLSX.writeFile(wb, `${buildFileName(opts.schoolName, 'Comprehensive Report')}.xlsx`);
};

export const generateAllExcelFile = (opts) => {
  const wb = buildComprehensiveExcelWB(opts);
  const fn = buildFileName(opts.schoolName, 'Comprehensive Report');
  const buf = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new File([buf], `${fn}.xlsx`, { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
};
