import { useEffect, useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import useApi from '../../hooks/useApi';
import { useAuth } from '../../context/AuthContext';
import toast from 'react-hot-toast';
import {
  HiOutlinePlus, HiOutlineSearch, HiOutlinePencil, HiOutlineTrash,
  HiOutlineDocumentReport, HiOutlineUser, HiOutlinePrinter, HiOutlineDownload,
  HiOutlineClipboardList,
} from 'react-icons/hi';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const API_BASE = import.meta.env.VITE_API_BASE_URL || (import.meta.env.DEV ? 'http://localhost:5000' : '');

/** Load an image URL as a data URL for embedding in PDF */
const loadImageAsDataUrl = async (url) => {
  if (!url) return null;
  try {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    await new Promise((resolve, reject) => { img.onload = resolve; img.onerror = reject; img.src = url; });
    const canvas = document.createElement('canvas');
    canvas.width = img.naturalWidth;
    canvas.height = img.naturalHeight;
    canvas.getContext('2d').drawImage(img, 0, 0);
    return { dataUrl: canvas.toDataURL('image/png'), width: img.naturalWidth, height: img.naturalHeight };
  } catch { return null; }
};

const PupilsList = () => {
  const { isAdmin, isTeacher, user, isPremium } = useAuth();
  const canEdit = isAdmin || isTeacher;
  const { get, del, loading } = useApi();
  const [pupils, setPupils] = useState([]);
  const [classes, setClasses] = useState([]);
  const [filters, setFilters] = useState({ search: '', class_id: '' });
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);

  const fetchPupils = useCallback(async () => {
    try {
      const params = { page, limit: 20 };
      if (filters.search) params.search = filters.search;
      if (filters.class_id) params.class_id = filters.class_id;

      const res = await get('/pupils', params, { silent: true });
      setPupils(res.data.pupils);
      setTotal(res.data.total);
    } catch { /* handled */ }
  }, [get, page, filters]);

  const fetchClasses = useCallback(async () => {
    try {
      const res = await get('/classes', null, { silent: true });
      setClasses(res.data || []);
    } catch { /* handled */ }
  }, [get]);

  useEffect(() => { fetchPupils(); }, [fetchPupils]);
  useEffect(() => { fetchClasses(); }, [fetchClasses]);

  const handleDelete = async (id, name) => {
    if (!window.confirm(`Remove ${name}?`)) return;
    try {
      await del(`/pupils/${id}`);
      toast.success('Pupil removed');
      fetchPupils();
    } catch { /* handled */ }
  };

  // ── Print Pupils Register (downloads PDF) ──
  const handlePrint = async () => {
    toast('Generating register…', { icon: '🖨️', duration: 1500 });

    // Fetch ALL pupils (not just current page)
    let allPupils = pupils;
    if (total > 20) {
      try {
        const params = { page: 1, limit: 9999 };
        if (filters.search) params.search = filters.search;
        if (filters.class_id) params.class_id = filters.class_id;
        const res = await get('/pupils', params, { silent: true });
        allPupils = res.data.pupils || [];
      } catch { /* fallback to current page */ }
    }

    const schoolName = user?.school_name || 'School Manager';
    const schoolLogo = user?.school_badge_url ? await loadImageAsDataUrl(`${API_BASE}${user.school_badge_url}`) : null;
    const brandingText = isPremium
      ? `Generated by ${schoolName} digital system on ${new Date().toLocaleDateString()}`
      : `Generated by School Manager © ${new Date().getFullYear()}`;
    const filterClassName = filters.class_id ? classes.find(c => c.id === filters.class_id)?.name : 'All Classes';

    const doc = new jsPDF();
    const pw = doc.internal.pageSize.getWidth();
    const ph = doc.internal.pageSize.getHeight();
    let y = 15;

    // Header bar
    doc.setFillColor(30, 58, 95);
    doc.rect(0, 0, pw, 10, 'F');
    doc.setFillColor(240, 173, 78);
    doc.rect(0, 10, pw, 2, 'F');

    if (schoolLogo) {
      const imgW = 20;
      const imgH = (schoolLogo.height / schoolLogo.width) * imgW;
      doc.addImage(schoolLogo.dataUrl, 'PNG', (pw - imgW) / 2, y, imgW, imgH);
      y += imgH + 5;
    }

    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(30, 58, 95);
    doc.text(schoolName.toUpperCase(), pw / 2, y, { align: 'center' });
    y += 8;
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(80, 80, 80);
    doc.text(`PUPILS REGISTER — ${filterClassName}`, pw / 2, y, { align: 'center' });
    y += 6;

    const males = allPupils.filter(p => p.gender === 'Male').length;
    const females = allPupils.filter(p => p.gender === 'Female').length;
    doc.setFontSize(9);
    doc.text(`Total: ${allPupils.length} | Boys: ${males} | Girls: ${females} | Generated: ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`, pw / 2, y, { align: 'center' });
    y += 8;

    doc.setDrawColor(200);
    doc.line(14, y, pw - 14, y);
    y += 5;

    const rows = allPupils.map((p, i) => {
      const dob = p.date_of_birth ? new Date(p.date_of_birth).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : '—';
      return [i + 1, `${p.first_name} ${p.last_name}`, p.class_name || '—', p.gender || '—', p.admission_number || '—', dob];
    });

    autoTable(doc, {
      startY: y,
      head: [['#', 'Name', 'Class', 'Gender', 'Admission #', 'Date of Birth']],
      body: rows,
      theme: 'grid',
      headStyles: { fillColor: [30, 58, 95], fontSize: 8, textColor: [255, 255, 255] },
      bodyStyles: { fontSize: 8, textColor: [50, 50, 50] },
      columnStyles: { 0: { cellWidth: 10 } },
    });

    // Footer
    doc.setFillColor(30, 58, 95);
    doc.rect(0, ph - 10, pw, 10, 'F');
    doc.setFillColor(240, 173, 78);
    doc.rect(0, ph - 12, pw, 2, 'F');
    doc.setFontSize(7);
    doc.setTextColor(255, 255, 255);
    doc.text(brandingText, pw / 2, ph - 5, { align: 'center' });

    doc.save(`Pupils_Register_${schoolName.replace(/\s+/g, '_')}.pdf`);
    toast.success('Register downloaded!');
  };

  // ── PDF Download ──
  const handleDownloadPDF = async () => {
    toast('Generating PDF…', { icon: '📄', duration: 1500 });
    // Fetch ALL pupils for export
    let allPupils = pupils;
    if (total > 20) {
      try {
        const params = { page: 1, limit: 9999 };
        if (filters.search) params.search = filters.search;
        if (filters.class_id) params.class_id = filters.class_id;
        const res = await get('/pupils', params, { silent: true });
        allPupils = res.data.pupils || [];
      } catch { /* fallback */ }
    }

    const schoolName = user?.school_name || 'School Manager';
    const schoolLogo = user?.school_badge_url ? await loadImageAsDataUrl(`${API_BASE}${user.school_badge_url}`) : null;
    const brandingText = isPremium
      ? `Generated by ${schoolName} digital system on ${new Date().toLocaleDateString()}`
      : `Generated by School Manager © ${new Date().getFullYear()}`;

    const filterClassName = filters.class_id ? classes.find(c => c.id === filters.class_id)?.name : 'All Classes';

    const doc = new jsPDF();
    let y = 15;

    // Header bar
    doc.setFillColor(30, 58, 95);
    doc.rect(0, 0, doc.internal.pageSize.getWidth(), 10, 'F');
    doc.setFillColor(240, 173, 78);
    doc.rect(0, 10, doc.internal.pageSize.getWidth(), 2, 'F');

    if (schoolLogo) {
      const imgW = 20;
      const imgH = (schoolLogo.height / schoolLogo.width) * imgW;
      doc.addImage(schoolLogo.dataUrl, 'PNG', (doc.internal.pageSize.getWidth() - imgW) / 2, y, imgW, imgH);
      y += imgH + 5;
    }

    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(30, 58, 95);
    doc.text(schoolName.toUpperCase(), doc.internal.pageSize.getWidth() / 2, y, { align: 'center' });
    y += 8;
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(80, 80, 80);
    doc.text(`PUPILS REGISTER — ${filterClassName}`, doc.internal.pageSize.getWidth() / 2, y, { align: 'center' });
    y += 6;

    const males = allPupils.filter(p => p.gender === 'Male').length;
    const females = allPupils.filter(p => p.gender === 'Female').length;
    doc.setFontSize(9);
    doc.text(`Total: ${allPupils.length} | Boys: ${males} | Girls: ${females} | Generated: ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`, doc.internal.pageSize.getWidth() / 2, y, { align: 'center' });
    y += 8;

    doc.setDrawColor(200);
    doc.line(14, y, doc.internal.pageSize.getWidth() - 14, y);
    y += 5;

    const rows = allPupils.map((p, i) => {
      const dob = p.date_of_birth ? new Date(p.date_of_birth).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : '—';
      return [i + 1, `${p.first_name} ${p.last_name}`, p.class_name || '—', p.gender || '—', p.admission_number || '—', dob];
    });

    autoTable(doc, {
      startY: y,
      head: [['#', 'Name', 'Class', 'Gender', 'Admission #', 'Date of Birth']],
      body: rows,
      theme: 'grid',
      headStyles: { fillColor: [30, 58, 95], fontSize: 8, textColor: [255, 255, 255] },
      bodyStyles: { fontSize: 8, textColor: [50, 50, 50] },
      columnStyles: { 0: { cellWidth: 10 } },
    });

    // Footer
    const pageH = doc.internal.pageSize.getHeight();
    doc.setFillColor(30, 58, 95);
    doc.rect(0, pageH - 10, doc.internal.pageSize.getWidth(), 10, 'F');
    doc.setFillColor(240, 173, 78);
    doc.rect(0, pageH - 12, doc.internal.pageSize.getWidth(), 2, 'F');
    doc.setFontSize(7);
    doc.setTextColor(255, 255, 255);
    doc.text(brandingText, doc.internal.pageSize.getWidth() / 2, pageH - 5, { align: 'center' });

    doc.save(`Pupils_Register_${schoolName.replace(/\s+/g, '_')}.pdf`);
  };

  // ── Print Blank Admission Form (generates a PDF) ──
  const handlePrintAdmissionForm = async () => {
    toast('Generating admission form…', { icon: '📋', duration: 1500 });
    const schoolName = user?.school_name || 'School Manager';
    const schoolLogo = user?.school_badge_url ? await loadImageAsDataUrl(`${API_BASE}${user.school_badge_url}`) : null;
    const brandingText = isPremium
      ? `Generated by ${schoolName} digital system on ${new Date().toLocaleDateString()}`
      : `Generated by School Manager © ${new Date().getFullYear()}`;

    const doc = new jsPDF();
    const pw = doc.internal.pageSize.getWidth();
    const ph = doc.internal.pageSize.getHeight();
    const margin = 14;
    let y = 14;

    // ─── School logo ───
    if (schoolLogo) {
      const imgW = 14;
      const imgH = (schoolLogo.height / schoolLogo.width) * imgW;
      doc.addImage(schoolLogo.dataUrl, 'PNG', (pw - imgW) / 2, y, imgW, imgH);
      y += imgH + 2;
    }

    // ─── School name ───
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(40, 40, 40);
    doc.text(schoolName.toUpperCase(), pw / 2, y, { align: 'center' });
    y += 6;

    // ─── Form title ───
    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(120, 120, 120);
    doc.text('PUPIL ADMISSION FORM', pw / 2, y, { align: 'center' });
    y += 5;

    // ─── Thin separator ───
    doc.setDrawColor(180, 180, 180);
    doc.setLineWidth(0.4);
    doc.line(margin, y, pw - margin, y);
    y += 6;

    // ─── Photo box (top-right, blank placeholder) ───
    const photoBoxW = 26;
    const photoBoxH = 32;
    const photoX = pw - margin - photoBoxW;
    const photoY = y;
    doc.setDrawColor(180, 180, 180);
    doc.setLineWidth(0.3);
    doc.roundedRect(photoX, photoY, photoBoxW, photoBoxH, 2, 2, 'S');
    doc.setFontSize(7);
    doc.setTextColor(180, 180, 180);
    doc.text('Passport', photoX + photoBoxW / 2, photoY + 13, { align: 'center' });
    doc.text('Photo', photoX + photoBoxW / 2, photoY + 18, { align: 'center' });

    // ─── Helper: section title (clean gray) ───
    const sectionTitle = (title) => {
      if (y > ph - 40) { doc.addPage(); y = 15; }
      doc.setFillColor(240, 240, 240);
      doc.roundedRect(margin, y, pw - margin * 2, 7, 1, 1, 'F');
      doc.setFontSize(8.5);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(60, 60, 60);
      doc.text(title, margin + 3, y + 5);
      y += 11;
    };

    // ─── Helper: blank field lines ───
    const drawFields = (fields, cols = 3) => {
      const gutter = 6;
      const usable = pw - margin * 2;
      const colW = (usable - gutter * (cols - 1)) / cols;
      let col = 0;
      fields.forEach((label) => {
        const x = margin + col * (colW + gutter);
        doc.setFontSize(6.5);
        doc.setFont(undefined, 'normal');
        doc.setTextColor(140, 140, 140);
        doc.text(label.toUpperCase(), x, y);
        doc.setDrawColor(210, 210, 210);
        doc.setLineWidth(0.2);
        doc.line(x, y + 6, x + colW, y + 6);
        col++;
        if (col >= cols) { col = 0; y += 11; }
      });
      if (col !== 0) y += 11;
    };

    // ─── 1. Personal Information ───
    sectionTitle('1.  PERSONAL INFORMATION');
    drawFields(['Surname (Last Name)', 'First Name', 'Other Names'], 3);
    drawFields(['Gender', 'Date of Birth', 'Nationality'], 3);
    drawFields(['Religion', 'Blood Group'], 2);

    // ─── 2. School Information ───
    sectionTitle('2.  SCHOOL INFORMATION');
    drawFields(['Admission Number', 'Class', 'Enrollment Type'], 3);
    drawFields(['Boarding / Day', 'Date of Admission'], 2);

    // ─── 3. Contact & Residence ───
    sectionTitle('3.  CONTACT & RESIDENCE');
    drawFields(['Address / Village', 'District'], 2);

    // ─── 4. Previous School ───
    sectionTitle('4.  PREVIOUS SCHOOL');
    drawFields(['School Name', 'Class Completed', 'Reason for Leaving'], 3);

    // ─── 5. Health & Medical ───
    sectionTitle('5.  HEALTH & MEDICAL INFORMATION');
    drawFields(['Blood Group', 'Allergies', 'Disabilities'], 3);
    drawFields(['Additional Medical Notes'], 1);

    // ─── 6. Emergency Contact ───
    sectionTitle('6.  EMERGENCY CONTACT');
    drawFields(['Contact Person Name', 'Phone Number', 'Relationship'], 3);

    // ─── 7. Parent / Guardian ───
    sectionTitle('7.  PARENT / GUARDIAN');
    drawFields(['Full Name', 'Phone', 'Email'], 3);
    drawFields(['Occupation', 'Address'], 2);

    // ─── Signature lines ───
    y += 8;
    if (y > ph - 45) { doc.addPage(); y = 20; }
    const sigW = (pw - margin * 2 - 20) / 3;
    ['Parent / Guardian Signature', 'School Admin Signature', 'Date'].forEach((label, i) => {
      const x = margin + i * (sigW + 10);
      doc.setDrawColor(160, 160, 160);
      doc.setLineWidth(0.3);
      doc.line(x, y + 18, x + sigW, y + 18);
      doc.setFontSize(7);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(130, 130, 130);
      doc.text(label, x + sigW / 2, y + 23, { align: 'center' });
    });

    // ─── Clean footer ───
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(margin, ph - 14, pw - margin, ph - 14);
    doc.setFontSize(6.5);
    doc.setTextColor(160, 160, 160);
    doc.text(brandingText, pw / 2, ph - 9, { align: 'center' });

    doc.save(`Admission_Form_${schoolName.replace(/\s+/g, '_')}.pdf`);
    toast.success('Admission form downloaded!');
  };

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <h1 className="text-2xl font-bold text-gray-900">Pupils</h1>
        <div className="flex items-center gap-2">
          <button onClick={handlePrintAdmissionForm} className="btn-secondary flex items-center gap-2 text-sm">
            <HiOutlineClipboardList className="w-4 h-4" /> Print Form
          </button>
          <button onClick={handlePrint} className="btn-secondary flex items-center gap-2 text-sm">
            <HiOutlinePrinter className="w-4 h-4" /> Print
          </button>
          <button onClick={handleDownloadPDF} className="btn-secondary flex items-center gap-2 text-sm">
            <HiOutlineDownload className="w-4 h-4" /> PDF
          </button>
          {canEdit && (
            <Link to="/pupils/new" className="btn-primary flex items-center gap-2">
              <HiOutlinePlus className="w-5 h-5" /> Add Pupil
            </Link>
          )}
        </div>
      </div>

      {/* Filters */}
      <div className="card">
        <div className="flex flex-col sm:flex-row gap-3">
          <select
            value={filters.class_id}
            onChange={(e) => { setFilters({ ...filters, class_id: e.target.value }); setPage(1); }}
            className="input-field sm:w-48"
          >
            <option value="">All Classes</option>
            {classes.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
          </select>
          <div className="relative flex-1">
            <HiOutlineSearch className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              type="text"
              placeholder="Search pupils..."
              value={filters.search}
              onChange={(e) => { setFilters({ ...filters, search: e.target.value }); setPage(1); }}
              className="input-field pl-10"
            />
          </div>
        </div>
      </div>

      {/* Table */}
      <div className="card overflow-hidden p-0">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="table-header">
                <th className="text-left p-3">Name</th>
                <th className="text-left p-3 hidden sm:table-cell">Class</th>
                <th className="text-left p-3 hidden md:table-cell">Gender</th>
                <th className="text-left p-3 hidden lg:table-cell">Admission #</th>
                <th className="text-right p-3">Actions</th>
              </tr>
            </thead>
            <tbody>
              {pupils.map((pupil) => (
                <tr key={pupil.id} className="border-b border-gray-50 hover:bg-gray-50 transition">
                  <td className="p-3">
                    <div className="flex items-center gap-3">
                      {pupil.photo_url ? (
                        <img
                          src={`${API_BASE}${pupil.photo_url}`}
                          alt={`${pupil.first_name} ${pupil.last_name}`}
                          className="w-9 h-9 rounded-full object-cover border border-gray-200"
                        />
                      ) : (
                        <div className="w-9 h-9 bg-primary-100 rounded-full flex items-center justify-center text-primary-600 font-semibold text-sm">
                          {pupil.first_name[0]}{pupil.last_name[0]}
                        </div>
                      )}
                      <div>
                        <p className="font-medium text-gray-800">{pupil.first_name} {pupil.last_name}</p>
                        <p className="text-xs text-gray-500 sm:hidden">{pupil.class_name || '—'}</p>
                      </div>
                    </div>
                  </td>
                  <td className="p-3 text-gray-600 hidden sm:table-cell">{pupil.class_name || '—'}</td>
                  <td className="p-3 text-gray-600 hidden md:table-cell">{pupil.gender || '—'}</td>
                  <td className="p-3 text-gray-600 hidden lg:table-cell">{pupil.admission_number || '—'}</td>
                  <td className="p-3 text-right">
                    <div className="flex items-center justify-end gap-1">
                      <Link
                        to={`/report-card/${pupil.id}`}
                        className="p-1.5 rounded hover:bg-blue-50 text-gray-400 hover:text-blue-600"
                        title="View Report Card"
                      >
                        <HiOutlineDocumentReport className="w-4 h-4" />
                      </Link>
                      {canEdit && (
                        <Link to={`/pupils/${pupil.id}/edit`} className="p-1.5 rounded hover:bg-gray-100 text-gray-500" title="Edit">
                          <HiOutlinePencil className="w-4 h-4" />
                        </Link>
                      )}
                      {isAdmin && (
                        <button onClick={() => handleDelete(pupil.id, `${pupil.first_name} ${pupil.last_name}`)} className="p-1.5 rounded hover:bg-red-50 text-red-500" title="Delete">
                          <HiOutlineTrash className="w-4 h-4" />
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
              {pupils.length === 0 && !loading && (
                <tr>
                  <td colSpan="5" className="text-center py-12 text-gray-400">
                    No pupils found. {canEdit && <Link to="/pupils/new" className="text-primary-500 hover:underline">Add your first pupil</Link>}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        {total > 20 && (
          <div className="flex items-center justify-between p-3 border-t border-gray-100">
            <span className="text-sm text-gray-500">{total} pupils total</span>
            <div className="flex gap-2">
              <button onClick={() => setPage(Math.max(1, page - 1))} disabled={page === 1} className="btn-secondary text-sm py-1.5 px-3">Previous</button>
              <button onClick={() => setPage(page + 1)} disabled={pupils.length < 20} className="btn-secondary text-sm py-1.5 px-3">Next</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default PupilsList;
